# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "10.10.10.50"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker-vm"
    vb.memory = "1024"
    vb.cpus = 2
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  config.vm.provision "shell", path: "docker.sh"
end
